basic/urls.py
from django.urls import path , include
from . import views
urlpatterns = [
    
    path('' , views.home , name='dashboard'),
    path('product'  ,views.product , name='product'),
    path('enquiry' , views.enquiry , name='enquiry'),
    path('employee'  , views.employee , name='employee'),
    path('stock' , views.stock , name='stock'),
    path('clients' , views.clients , name='clients'),
    path('serviceSlip' , views.serviceSlip , name='serviceSlip'),
    path('followup' , views.followup , name='followup'),
    path('profile' , views.profilePage , name='profile'),
    path('service' , views.service , name='service'),
    path('reports' , views.reports, name='reports'),
   
    
    # update
    path('enquiry/<str:pk>/', views.enquiryUpdate , name = 'enquiryUpdate'),
    path('product/<str:pk>/' , views.productEnquiry , name='productEnquiry'),
    path('employee/<str:pk>/' , views.employeeUpdate , name = 'employeeUpdate'),
    path('client/<str:pk>/' , views.clientUpdate , name='clientUpdate'),
    path('serviceSlip/<str:pk>/' , views.updateSlip , name='updateSlip'),

    #delete 
    
    path('deleteEmployee/<str:pk>/', views.deleteEmployee , name = 'deleteEmployee'),
    path('deleteProduct/<str:pk>/', views.deleteProduct , name = 'productDelete'),
    path('deleteEnquiry/<str:pk>/', views.deleteEnquiry , name = 'enquiryDelete'),
    path('deleteClient/<str:pk>/', views.deleteClient , name = 'clientDelete'),
    path('deleteSlip/<str:pk>/' , views.deleteSlip , name='deleteSlip'),
    #auth
    path('login' , views.loginPage , name='loginPage'),
    path('register' , views.register , name='register'),
    path('logout' , views.logoutPage , name='logoutPage')
   
    

]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = 'calendarapp'
urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),
]

salon/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
    path('calendar/' , include('calendarapp.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basic/forms.py
from django.forms import ModelForm
from basic.models import Product , Enquiry , Employee , Client  , Slip ,Service
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewService(ModelForm):
    class Meta:
        model = Service
        fields = '__all__'
        
class NewSlip(ModelForm):
    class Meta:
        model = Slip
        fields = '__all__'
        

class NewClient(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

class SignUpForm(UserCreationForm):
   
    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2', )


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class EnquiryForm(ModelForm):
    class Meta:
        model = Enquiry
        fields = '__all__'


class EmployeForm(ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

      

basic/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import Enquiry , Product , Employee , Client , Slip , Service , Category
from .forms import ProductForm , EnquiryForm , EmployeForm , SignUpForm  , NewClient , NewSlip , NewService
from django.contrib.auth import login , logout , authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# Create your views here.
from django.contrib.auth.decorators import login_required
from datetime import datetime



def reports(request):
    warm = Enquiry.objects.filter(response ='warm').count()
    cold = Enquiry.objects.filter(response ='cold').count()
    normal = Enquiry.objects.filter(response ='normal').count()
    print(warm)
    params = {
        'warm': warm,
        'cold' : cold , 
        'normal': normal
    }
    return render(request , 'basic/reports.html' , params)
def service(request):
    service = Service.objects.all()
    form = NewService()
    if request.method == 'POST':
        form = NewService(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            return render(request , 'basic/404.html')
    else:
        form = NewService()
    params = {
        'service': service,
        'form' : form,
        'today' : today
    }
    return render(request , 'basic/forms/service.html', params)
def followup(request):
    obj = Product.objects.all()
    cli = Client.objects.all()
    
    l1 = []
    for i in obj:
        if i.quantity <5:
            l1.append(i)
    
   
    params = {
        'pro' : l1,
        'cli': cli    }
    return render(request , 'basic/followup/followupBase.html' , params)
@login_required(login_url='loginPage')
def cover(request):
    return render(request , 'basic/cover.html')

def loginPage(request):
    if request.method == 'POST':
        uname = request.POST.get('uname')
        pwd = request.POST.get('pwd')

        user = authenticate(username=uname , password = pwd)

        if user is not None:
            login(request , user)
            return redirect('dashboard')
        else:
            return render(request , 'basic/404.html')
    else :
        pass

    return render(request , 'basic/signin.html')

def register(request):
    form = SignUpForm()
    if request.method=='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('calendarapp:index')
        else:
            return HttpResponse("Nai hua bhau")
    else :
        form = SignUpForm()
    params = {
    'form': form
    }

    return render(request , 'basic/register.html' , params )
    
     
def profilePage(request):
    return render(request , 'basic/profile.html')

def logoutPage(request):
    logout(request)
    return redirect('loginPage')
    
@login_required(login_url='loginPage')
def home(request):
    today = datetime.now()
    enq = Enquiry.objects.all()
    service  = Service.objects.all()
    pro = Product.objects.all().order_by('quantity')
    empCount = Employee.objects.count()
    clients = Client.objects.count()
    services = Service.objects.count()
    params = {
        'enq': enq ,
        'pro' : pro,
        'empCount' : empCount,
        'Clients' : clients,
        'services': services,
        'service': service, 
        'today' : today
    }
    return render(request , 'basic/dashboard.html' , params)


@login_required(login_url='loginPage')
def enquiry(request):
    enq = Enquiry.objects.all()
    form = EnquiryForm()
    if request.method == 'POST':
        form = EnquiryForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('dashboard')
        else :
            return HttpResponse('<h3> Try again </h3>')
    else :
        form = EnquiryForm()
    params = {
        'form' : form ,
        'pro' : enq
    }

    return render(request , 'basic/enquiry.html' , params)
@login_required(login_url='loginPage')
def enquiryUpdate(request , pk):
    enq = Enquiry.objects.get(id = pk)
    
    if request.method == 'POST':
        form = EnquiryForm(request.POST , instance=enq)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            return HttpResponse('not found')
    else:
        form = EnquiryForm(instance= enq)
    params = {
        'form' : form
    }
    return render(request , 'basic/enquiryForm.html' , params)

@login_required(login_url='loginPage')
def deleteEnquiry(request , pk):
    pro = Enquiry.objects.get(id=pk)
    if request.method=='POST':
        pro.delete()
        return redirect('enquiry')
    params = {
        'item': pro
    }
    return render(request , 'basic/deleteEnquiry.html' , params )


@login_required(login_url='loginPage')
def product(request):
    enq = Product.objects.all()
    form = EnquiryForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else :
            return HttpResponse('<h3> Try again </h3>')
    else :
        form = ProductForm()
    params = {
        'form' : form ,
        'pro' : enq
    }

    return render(request , 'basic/product.html' , params)
    

@login_required(login_url='loginPage')
def productEnquiry(request , pk):
    enq = Product.objects.get(id = pk)
    
    if request.method == 'POST':
        form = ProductForm(request.POST , instance=enq)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            return HttpResponse('not found')
    else:
        form = ProductForm(instance= enq)
    params = {
        'form' : form
    }
    return render(request , 'basic/productForm.html' , params)
@login_required(login_url='loginPage')
def employee(request):
    emp = Employee.objects.all()
    if request.method == 'POST':
        form = EmployeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else :
            return render(request , 'basic/404.html')
    else:
        form = EmployeForm()
    params = {
        'form': form,
        'pro': emp
    }
    return render(request , 'basic/employee.html' , params)
@login_required(login_url='loginPage')
def employeeUpdate(request , pk):
    enq = Employee.objects.get(id = pk)
    
    if request.method == 'POST':
        form = EmployeForm(request.POST , instance=enq)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            return HttpResponse('not found')
    else:
        form = EmployeForm(instance= enq)
    params = {
        'form' : form
    }
    return render(request , 'basic/empForm.html' , params)
@login_required(login_url='loginPage')
def stock(request):
    pro = Product.objects.all()
    params = {
        'stock': pro
    }
    return render(request , 'basic/album.html' , params)
@login_required(login_url='loginPage')
def clients(request):
    cli = Client.objects.all()
    form = NewClient()
    if request.method=='POST':
        form = NewClient(request.POST)
        if form.is_valid():
            form.save()
            return redirect('calendarapp:calendar')
        else :
            return render(request , 'basic/404.html')
    else : 
        form = NewClient()
        
    params = {
        'pro' : cli,
        'form' : form
    }
    return render(request , 'basic/forms/newClient.html' , params)

def clientUpdate(request , pk):
    enq = Client.objects.get(id = pk)
    
    if request.method == 'POST':
        form = NewClient(request.POST , instance=enq)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            return HttpResponse('not found')
    else:
        form = NewClient(instance= enq)
    params = {
        'form' : form
    }
    return render(request , 'basic/forms/updateClient.html' , params)
def deleteClient(request , pk):
    cli = Client.objects.get(id=pk)
    if request.method == 'POST':
        cli.delete()
        return redirect('clients')
    params = {
        'item': cli
    }
    return render(request , 'basic/forms/deleteClient.html' , params)



@login_required(login_url='loginPage')
def deleteEmployee(request , pk):
    Emp = Employee.objects.get(id=pk)
    if request.method == 'POST':
        Emp.delete()
        return redirect('employee')
       
    
    params = {
        'item': Emp
    }

    return render(request, 'basic/deleteEmployee.html' , params)
@login_required(login_url='loginPage')
def deleteProduct(request , pk):
    pro = Product.objects.get(id=pk)
    if request.method=='POST':
        pro.delete()
        return redirect('product')
    params = {
        'item': pro
    }
    return render(request , 'basic/deleteProduct.html' , params)


def serviceSlip(request):
    cli = Slip.objects.all()
    form = NewSlip()
    if request.method=='POST':
        form = NewSlip(request.POST)
        if form.is_valid():
            form.save()
            return redirect('serviceSlip')
        else :
            return render(request , 'basic/404.html')
    else : 
        form = NewSlip()
        
    params = {
        'pro' : cli,
        'form' : form
    }
    return render(request , 'basic/forms/serviceSlip.html' , params)

def updateSlip(request , pk):
    slip = Slip.objects.get(id=pk)
    if request.method == 'POST':
        form = NewSlip(request.POST , instance=slip)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:

basic/templates/basic/calander/add_member.html
{% extends 'basic/base.html' %}



{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
</main>
{% endblock %}

basic/templates/basic/calander/calanderStyle.html
<style>
.calendar {
    
    
    margin-top: 20px;
    font-size: 13px;
    object-fit: contain;
  }
  
  .calendar tr, .calendar td {
    border: 1px solid black;
    box-shadow: 2px 2px;
    min-width: 100px;
    min-height: 100px;
  }
  .calendar a{
    
    font-size: 13px;
  }
  .calendar tbody{
     background-color: #fff;
   padding: 20px;
   padding-left: 15%;
   padding-right: 15%;
   overflow: hidden;
  }
  .calendar th {  
    padding: 5px;
    text-align: center;
    font-size: 30px;
  }
  
  .calendar td {
    width: 100px;
    height: 70px;
    padding: 20px 0px 0px 5px;
    font-size: 20px;
  }
  
  .month {
    font-size: 25px;
  }
  
  .date {
    font-size: 16px;
  }
  
  ul {
    
    padding: 5px 5px 5px 20px;
  }
  
 

  .left {
    float: left;
  }
  
  .right {
    float: right;
  }
  
  .clearfix {
    margin: 15px;
  }
</style>

basic/templates/basic/calander/calendar.html
{% extends 'basic/base.html' %}

{% block content %}


<div class='container-fluid py-4' style="background-color: grey;">
<div class="clearfix container-fluid" >

      

    <div style="color: #4E73DF;" class='container ' > 
   
    <a class="btn btn-primary right mr-2 mt-1 " href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
        <a class="btn btn-primary right mr-2 mt-1" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
        <a class="btn btn-success right mr-2 mt-1" href="{% url 'calendarapp:event_new' %}"> + New Event </a>
        <h1 class="h3 mb-0 " style="color:white;" >Your Appointments</h1>
       
            {{ calendar}}
    </div>
   

   
</div>
</div>

 

                





{% include 'basic/calander/calanderStyle.html' %}
 
{% endblock content %}

basic/templates/basic/calander/event-details.html
{% extends 'basic/base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
        </div>
        
        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>                  
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
</main>
{% endblock %}

basic/templates/basic/calander/event.html
{% extends 'basic/base.html' %}

{% block content %}
 <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
</main>
{% endblock %}

basic/templates/basic/calander/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'basic/base.html' %}



{% block content %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
    </main>
{% endblock content %}